

#' Compile Mplus Data for Dejonckheere Project
#'
#' Creates a tidy dataset for the Dejonckheere Project containing analyses from multiple Mplus objects. This can then be used in the [MplusReadR::dejon_apa_table()] function, or can be saved separately.
#'
#' @import dplyr
#' @param Mplus_file An Mplus object for the Dejonckheere project generated by the Mplus Automation package from Mplus output using the [MplusAutomation::readModels()] function.
#' @param model_type One of 'null', 'univariate', or 'bivariate'.
#' @param rounding A value between 0 and 3. Defaults to 2.
#' @param parameters Parameters in the Mplus output, without the variable name at the start e.g. NAMEAN is MEAN, NASDW is SDW.
#' Must be in capitals, and exactly like it is in the original output. These can be found using [MplusReadR::mplus_check_params()].
#' Defaults to all available parameters.
#' @param variables Variables from the Mplus output. Exact variable names can be found using [MplusReadR::mplus_check_params()]. Defaults to all available variables.
#' @param paramheaders Parameter headers from the Mplus output. Exact parameter headers can be found using [MplusReadR::mplus_check_params()]. For null models,
#' defaults to New.Additional.Parameters. For univariate and bivariate models, defaults to Z.ON and R2.
#' @param outcomes Outcome variables in the Mplus output. Available outcomes can be found using [MplusReadR::mplus_check_params()]. Defaults to all outcomes.
#' @param standardized Whether standardized or unstandardized output should be used for univariate and bivariate models. Defaults to TRUE.
#' @return A tibble containing specified variables and parameters from multiple Mplus models.
#'
#' @seealso [MplusReadR::dejon_apa_table()] [MplusAutomation::readModels()] [MplusReadR::mplus_check_params()]

# This function takes the tidy data function and applies it to multiple mplus files in an mplus model list
dejon_compile <- function(Mplus_file, model_type, rounding = 2, parameters = NULL, variables = NULL, paramheaders = NULL, outcomes = NULL, standardized = TRUE){

  # Initialising the variable used in the loop below
  data <- tibble()

  # Add all the data from all the tables into one big dataset
  for(n in 1:length(Mplus_file)){
      temp_data <- dejon_tidy(Mplus_file, model_n = n, model_type = model_type, rounding = rounding, parameters = parameters,
                                   variables = variables, paramheaders = paramheaders, outcomes = outcomes, standardized = standardized)
      data <- rbind(data, temp_data)
  }

  # Assign dataset number based on value of dataset title
  title <- as_tibble(unique(data$dataset_title))
  title <- title %>%
    mutate(dataset = seq.int(nrow(.))) %>%
    rename(dataset_title = value)
  data <- data %>%
    full_join(title, by = "dataset_title") %>%
    select(dataset, everything()) %>%
    arrange(dataset, variable)

  # saving our new dataset
  return(data)
}
