

#' Check Model Convergence
#'
#' Determines whether any of the Mplus models did not converge. Models that do not converge will not report confidence intervals. This is used to determine whether a model converged.
#'
#' @import purrr
#'
#' @param Mplus_file An Mplus object generated by the Mplus Automation package from Mplus output using the \code{\link[MplusAutomation]{readModels}} function. This can contain multiple models.
#'
#' @return A tidy dataset indicating whether each of the models converged.
#' @export

# Check whether each model in an Mplus list converged
mplus_converge <- function(Mplus_file, dir = getwd()){

  # Initialising the variable used in the loop below
  data <- tibble()

  # Check for each dataset in the Mplus file, whether one of the columns contains confidence intervals. If not, indicate that it did not converge.
  for (model_n in 1:length(Mplus_file)) {

    colnames <- paste0(colnames(Mplus_file[[model_n]]$parameters$unstandardized), collapse = " ")

    data[model_n, "list_number"] <- model_n # Makes it easy to determine which model in the list of models it was
    data[model_n, "file_name"] <- shorten_file_name(names(Mplus_file[model_n])) # 'shorten_file_name()' function can be found in 'mplus_helper_functions.R'
    data[model_n, "dataset_title"] <- as.character(Mplus_file[[model_n]]$input$title)
    data[model_n, "converged_cis"] <- ifelse(grepl("lower_2.5ci", colnames), "TRUE", "FALSE")
    data[model_n, "converged_text"] <- any(grep(pattern = "THE MODEL ESTIMATION TERMINATED NORMALLY",
                                                readLines(paste0(dir, "/", data[model_n, "file_name"]))))

  }

  # Remove unnecessary columns (we only need to know which converged, not the method of checking convergence)
  data <- data %>%
    mutate(converged = ifelse(converged_cis == TRUE | converged_text == TRUE, yes = TRUE, no = FALSE)) %>%
    select(-c("converged_cis", "converged_text"))


  # Check if dataset titles exist in the Mplus_file
  if(all(data$dataset_title == "")){
    data <- data %>%
      select(-dataset_title)

    warning("The Mplus file/s do not appear to contain dataset titles so the 'dataset title' column has been removed.")
  }


  return(data)
}

#' Remove Non-Converged Models
#'
#' Checks whether any models in the list of Mplus models did not converge, and removes those that did not converge.
#'
#' @param Mplus_file An Mplus object generated by the Mplus Automation package from Mplus output using the \code{\link[MplusAutomation]{readModels}} function. This can contain multiple models.
#'
#' @return The original Mplus output excluding the non-converged models.
#'
#' @export
#'
#' @seealso \code{\link[MplusReadR]{mplus_converge}}

# Check whether each model in an Mplus list converged and remove those that did not
mplus_remove_converge <- function(Mplus_model, dir = getwd()){
  # Create a table of values indicating which models did or did not converge
  data <- mplus_converge(Mplus_model, dir = dir)

  # Create a list of models that did not converge and save names
  not_converged <- as_vector(data %>%
                               filter(converged == FALSE) %>%
                               select(file_name))

  # Remove these from the original Mplus model list
  Mplus_model <- Mplus_model[names(Mplus_model) %in% not_converged == FALSE]

  # Return (spit out) the new filtered Mplus model list
  return(Mplus_model)

}
