

#' Check Parameters
#'
#' Checks the options available to select in [MplusReadR::mplus_compile()] or [MplusReadR::dejon_compile()].
#'
#' @param Mplus_file An mplus object generated by the Mplus Automation package from Mplus output using the [MplusAutomation::readModels()] function.
#' @param parameter_type One of 'parameters', 'paramheader' or 'display'. It is also possible to select 'outcomes' and 'variables' for Dejonckheere project models.
#' @param standardized Whether standardized or unstandardized output should be used for univariate and bivariate models. Defaults to TRUE.
#' @param project Whether the parameters are for the Dejon project or another project. One of 'dejon', 'other'. Defaults to 'other'.
#' @return A list of available options for [MplusReadR::mplus_compile()] or [MplusReadR::dejon_compile()].
#' @export


mplus_check_params <- function(Mplus_file, parameter_type, standardized = TRUE, project = "other"){

if (parameter_type == "variables") {

  check_vars(Mplus_file = Mplus_file)
}

  if (parameter_type == "parameters") {

    check_parameters(Mplus_file = Mplus_file, standardized = standardized)
  }

  else if (parameter_type == "outcomes") {

    check_outcomes(Mplus_file = Mplus_file)

  }

  else if (parameter_type == "paramheader") {

    check_paramheader(Mplus_file = Mplus_file, standardized = standardized, project = project)
  }

  else if(parameter_type == "display") {

    check_display(Mplus_file = Mplus_file, standardized = standardized)


  }
}


#Checks what vars are available
check_vars <- function(Mplus_file){

  # Initialising the variable used in the loop below
  data <- tibble()

  # Add all the data from all the tables into one big dataset
  for(n in 1:length(Mplus_file)){
    temp_data <- Mplus_file[[n]]$input$variable$usevar %>%
      as.character() %>%
      strsplit("\\ ") %>%
      unlist() %>%
      .[. != "PID"] %>%
      as_tibble()
    data <- rbind(data, temp_data)
  }
  # keep only unique
  data <- unique(data$value)

  # saving our new dataset
  return(data)
}



# Checks what parameters are available
check_parameters <- function(Mplus_file, standardized = TRUE){

  # Initialising the variable used in the loop below
  data <- tibble()

  if(standardized == FALSE){
  # Add all the data from all the tables into one big dataset
  for(n in 1:length(Mplus_file)){
    temp_data <- as_tibble(Mplus_file[[n]]$parameters$unstandardized$param)
    data <- rbind(data, temp_data)
  }
  }
  else if (standardized == TRUE){
    for(n in 1:length(Mplus_file)){
      temp_data <- as_tibble(Mplus_file[[n]]$parameters$stdyx.standardized$param)
      data <- rbind(data, temp_data)
    }
  }

  # keep only unique
  data <- unique(data$value)

  # saving our new dataset
  return(data)
}


check_outcomes <- function(Mplus_file){

  # Initialising the variable used in the loop below
  data <- tibble()

  # Add all the data from all the tables into one big dataset
  for(n in 1:length(Mplus_file)){
  temp_data <- as_tibble(gsub(".*[ =]([^;]+)[;].*", "\\1", Mplus_file[[n]]$input$define[3]))
  data <- rbind(data, temp_data)
  }

  # keep only unique
  data <- unique(data$value)

  # saving our new dataset
  return(data)
}


check_paramheader <- function(Mplus_file, standardized, project){

  if(project == "dejon"){

    # Initialising the variable used in the loop below
    data <- tibble()

    if(standardized == TRUE) {
      for(n in 1:length(Mplus_file)){
        temp_data <- as_tibble(Mplus_file[[n]]$parameters$stdyx.standardized$paramHeader)
        data <- rbind(data, temp_data)
      }

    }

    else if (standardized == FALSE){
      for(n in 1:length(Mplus_file)){
        temp_data <- as_tibble(Mplus_file[[n]]$parameters$unstandardized$paramHeader)
        data <- rbind(data, temp_data)
      }
    }

    # keep only unique
    data <- unique(data$value)
  }

  else if (project == "other"){

    data <- mplus_compile(Mplus_file = Mplus_file, standardized = standardized)
    data <- unique(data$paramHeader)
  }

    # saving our new dataset
    return(data)

}

check_display <- function(Mplus_file, standardized){

  data <- mplus_compile(Mplus_file = Mplus_file, standardized = standardized)
  data <- colnames(data)

  # Returning column names
  return(data)
}

