#' Compile Mplus Data
#'
#' Creates a tidy dataset containing analyses from multiple Mplus objects. This can then be used in the `mplus_apa_table()` function, or can be saved separately.
#'
#' @import dplyr
#' @param Mplus_file An mplus object generated by the Mplus Automation package from Mplus output using the [MplusAutomation::readModels()] function.
#' @param rounding A value between 0 and 3. Defaults to 2.
#' @param param_header Parameter headers from the Mplus output. Exact parameter headers can be found using [MplusReadR::mplus_check_params()].
#' @param parameter Parameters in the Mplus output. These can be found using [MplusReadR::mplus_check_params()]).
#' Defaults to all available parameters.
#' @param display How many columns should be displayed. Choose from "all", "minimal", "descriptives" or manually specify which columns should be displayed. Available columns can be found using [MplusReadR::mplus_check_params()].
#' @param standardized Whether standardized or unstandardized output should be used for univariate and bivariate models. Defaults to TRUE.
#' @param converged If TRUE, removes non-converged models.
#' @param define Displays a column containing information from the 'define' input in the Mplus file. Defaults to FALSE.
#' @param dir Directory of the data.
#' @return A tibble containing specified variables and parameters from multiple Mplus models.
#' @export


# This function takes the tidy data function and applies it to multiple mplus files in an mplus model list
mplus_compile <- function(Mplus_file,
                          rounding = 2,
                          param_header = NULL,
                          parameter = NULL,
                          display = "all",
                          standardized = TRUE,
                          converged = TRUE,
                          define = FALSE,
                          dir = getwd()){

  # Initializing the variable used in the loop below
  data <- tibble()

  # Remove non-converged models
  if(converged == TRUE){
    Mplus_file_clean <- mplus_remove_converge(Mplus_file, dir = dir)
    if(length(Mplus_file_clean) < length(Mplus_file)){
      message(paste("It appears",(length(Mplus_file)-length(Mplus_file_clean)), "models did not converge. These were removed. Run mplus_converge(Mplus_file) to check these."))
    }
  }

  if(converged == FALSE){
    Mplus_file_clean <- Mplus_file

    none_converged_models <- Mplus_file %>%
        mplus_converge(dir = dir) %>%
        filter(converged == FALSE)

    if(nrow(none_converged_models) > 0){
      warning(paste0("There are non-converged models in this list. Run mplus_converge() to check these, or set converged = TRUE to remove automatically."))
    }
  }


  # Add all the data from all the tables into one big dataset
  for(n in 1:length(Mplus_file_clean)){

    temp_data <- mplus_tidy(Mplus_file_clean, model_n = n, rounding = rounding, parameter = parameter, param_header = param_header, standardized = standardized, define = define)
    data <- rbind(data, temp_data)
  }

  # Assign dataset number based on value of dataset title
  title <- as_tibble(unique(data$dataset_title))
  title <- title %>%
    mutate(dataset = seq.int(nrow(.))) %>%
    rename(dataset_title = value)
  data <- data %>%
    full_join(title, by = "dataset_title") %>%
    select(dataset, everything()) %>%
    arrange(dataset)

  ##### Display options for extra columns ####

  if(length(display) == 1){

    if(display == "all"){}

    else if(display == "minimal"){

      # Check that all the required columns needed for 'minimal' exist in the dataset
      minimal_columns <- c("dataset", "dataset_title", "paramHeader", "param", "est", "lower_2.5ci", "upper_2.5ci")

      if(length(setdiff(minimal_columns, colnames(data))) > 0){
        warning(paste0("Some of the columns required for this theme do not appear to be present in the dataset.
                     These are: ", setdiff(minimal_columns, colnames(data)),". Reverting to default: display = \"all\"."))
      }

      # If all the columns exist, select only these columns
      else if(length(setdiff(minimal_columns, colnames(data))) == 0){

        data <- data %>%
          select(dataset, dataset_title, paramHeader, param, est, lower_2.5ci, upper_2.5ci)

      }
    }

    else if(display == "descriptives"){

      # Check that all the required columns needed for 'descriptives' exist in the dataset
      descript_columns <- c("dataset", "dataset_title", "paramHeader", "T", "N", "param", "est", "lower_2.5ci", "upper_2.5ci")

      if(length(setdiff(descript_columns, colnames(data))) > 0){
        warning(paste0("Some of the columns required for this theme do not appear to be present in the dataset.
                     These are: ", setdiff(descript_columns, colnames(data)),". Reverting to default: display = \"all\"."))
      }

      # If all the columns exist, select only these columns
      else if(length(setdiff(descript_columns, colnames(data))) == 0){

        data <- data %>%
          select(dataset, dataset_title, paramHeader, `T`, N, param, est, lower_2.5ci, upper_2.5ci)

      }
    }

    else {

      # If the columns do not exist (there are names in do_not_display that are not column names)
      if(length(setdiff(display, colnames(data))) > 0){

        warning(paste("The column you have specified does not appear to be present in the dataset:", setdiff(display, colnames(data)), "Displaying all columns."))

      }
      else if(length(setdiff(display, colnames(data))) == 0){
        # Filter by display columns
        data <- data %>% select(display)
      }
    }

  }

  # If the user wants to specify the columns themselves
  else {

    # If the columns do not exist (there are names in do_not_display that are not column names)
    if(length(setdiff(display, colnames(data))) > 0){

      warning(paste("The following columns you have specified do not appear to be present in the dataset:", setdiff(display, colnames(data)), "Displaying all columns."))

    }
    else if(length(setdiff(display, colnames(data))) == 0){
      # Filter by display columns
      data <- data %>% select(display)
    }
  }


  # saving our new dataset
  return(data)
}
