#' Compile Mplus Data (NEW)
#'
#' Creates a tidy dataset containing analyses from multiple Mplus objects. This can then be used in the mplus_apa_table() function, or can be saved separately.
#'
#' @import dplyr
#' @param Mplus_file An mplus object generated by the Mplus Automation package from Mplus output using the [MplusAutomation::readModels()] function.
#' @param rounding a value between 0 and 3. Defaults to 2.
#' @param param_header parameter headers from the Mplus output. Exact parameter headers can be found using mplus_check_parameters(). For null models,
#' defaults to New.Additional.Parameters. For univariate and bivariate models, defaults to Z.ON and R2.
#' @param parameter parameters in the Mplus output, without the variable name at the start e.g. NAMEAN is MEAN, NASDW is SDW.
#' Must be in capitals, and exactly like it is in the original output. These can be found using mplus_check_parameters().
#' Defaults to all available parameters.
#' @param display How many columns should be displayed. Choose from "all", "minimal", "descriptives" or manually specify which columns should be displayed.
#' @param standardized Whether standardised or unstandardised output should be used for univariate and bivariate models. Defaults to TRUE.
#' @param converged If TRUE, removes non-converged models.
#' @return A tibble containing specified variables and parameters from multiple Mplus models.

# This function takes the tidy data function and applies it to multiple mplus files in an mplus model list
mplus_compile <- function(Mplus_file, rounding = 2, param_header = NULL, parameter = NULL, display = "all", standardized = TRUE, converged = TRUE){

  # Initialising the variable used in the loop below
  data <- tibble()

  # Remove non-converged models
  if(converged == TRUE){
    Mplus_file <- remove_no_converge(Mplus_file)
  }

  if(converged == FALSE){
    none_converged_models <- Mplus_file %>%
        model_converge() %>%
        filter(converged == FALSE)

    if(nrow(none_converged_models) > 0){
      warning(paste0("There are non-converged models in this list. Run model_converge() to check these, or set converged = TRUE to remove automatically."))
    }
  }


  # Add all the data from all the tables into one big dataset
  for(n in 1:length(Mplus_file)){

    temp_data <- mplus_tidy(Mplus_file, model_n = n, rounding = rounding, parameter = parameter, param_header = param_header, display = display, standardized = standardized)
    data <- rbind(data, temp_data)
  }

  # Assign dataset number based on value of dataset title
  title <- as_tibble(unique(data$dataset_title))
  title <- title %>%
    mutate(dataset = seq.int(nrow(.))) %>%
    rename(dataset_title = value)
  data <- data %>%
    full_join(title, by = "dataset_title") %>%
    select(dataset, everything()) %>%
    arrange(dataset)

  # saving our new dataset
  return(data)
}
